"""
Our beta against the one published value we can pin, at a = 0.71.

Lushnikov, Silantyev and Siegel, arXiv:2010.01201, study exactly this frozen
profile on the circle, their Eq. (9), and measure the algebraic tail of its
spectrum. Their `p_b` is our `beta`: both are the exponent of |f_k| ~ k^-beta
generated by the derivative discontinuity at the stagnation point antipodal to
the singularity. Their Table 2 tabulates it, but that table does not render in
the arXiv PDF and ar5iv truncates before reaching it. One value survives in
their running text, on their page 42:

    a = 0.71:   p_b = 9.32592

obtained from a two domain least squares fit to the spectrum. That is exactly
the kind of wide window spectral fit finding 10 showed to be biased low by
about 1 percent, so the comparison is worth making: our beta comes from the
local relation beta = 1 + (c2 - 1)/(a c2) with c2 read off the profile and
corrected by the exact c1 = 1/(1-a), never from a fit to the spectrum.

The two methods share nothing. If they agree, their fit was fine here. If ours
sits systematically above, the correction to their published number is the
size of the gap.

a = 0.75 is carried alongside as an anchor, since finding 12 already puts it at
beta = 4.2128337. Whatever this script returns there is the measure of what its
answer at 0.71 is worth.

Note that a = 0.71 sits just above their a_c = 0.6890665337007457, where the
frozen branch begins, so the simulation seeded guess is at its worst. If Newton
fails to land, that is the answer to report, not a number to force.

    python beta_lss.py
"""

import numpy as np

import dg
from profile_eq import guess_from_simulation, newton, simulate

P_B_LSS_071 = 9.32592          # their page 42, from the spectral fit


def evaluate(g, field, x):
    """Spectral interpolation of `field` at an arbitrary point x."""
    fh = g.fwd(field)
    c = 2.0 * fh / g.N
    c[0] = fh[0] / g.N
    c[-1] = fh[-1] / g.N
    k = np.arange(len(c))
    return float(np.real(np.sum(c * np.exp(1j * k * x))))


def zeros_of_U(g, f, a):
    """The stagnation points, with c = Hf and mu = (c-1)/(a c) at each."""
    U, Hf, _ = dg.fields(g, f)
    out = []
    for i in np.flatnonzero(np.sign(U) != np.sign(np.roll(U, -1))):
        x0, x1 = g.x[i], g.x[(i + 1) % g.N]
        if x1 < x0:
            x1 += 2.0 * np.pi
        u0, u1 = U[i], U[(i + 1) % g.N]
        x = x0 + (x1 - x0) * u0 / (u0 - u1)
        for _ in range(60):
            du = evaluate(g, Hf, x)
            if du == 0.0:
                break
            step = evaluate(g, U, x) / du
            x -= step
            if abs(step) < 1e-15:
                break
        c = evaluate(g, Hf, x)
        out.append((x % (2.0 * np.pi), c, (c - 1.0) / (a * c)))
    return sorted(out, key=lambda r: r[2])


def collect(a, ns):
    c1s, c2s, used = [], [], []
    for n in ns:
        g, out = simulate(a, n=n, w_max=1e6)
        f0, _ = guess_from_simulation(g, out)
        f, hist, ok = newton(g, f0, a)
        if not ok:
            continue
        z = zeros_of_U(g, f, a)
        if len(z) == 2:
            c1s.append(z[0][1])
            c2s.append(z[1][1])
            used.append(n)
    return np.array(c1s), np.array(c2s), used


def corrected(a, ns):
    c1, c2, used = collect(a, ns)
    if len(c1) < 3:
        return np.nan, np.nan, np.nan, used
    exact = 1.0 / (1.0 - a)
    s, b = np.polyfit(c1, c2, 1)
    r = c2 - (s * c1 + b)
    ss = ((c2 - c2.mean()) ** 2).sum()
    r2 = 1.0 - (r ** 2).sum() / ss if ss > 0 else np.nan
    per_point = c2 - s * (c1 - exact)
    return s * exact + b, float(np.std(per_point)), r2, used


print(__doc__.split("    python")[0])
print("=" * 74)

NS = (1024, 1536, 2048, 3072)
print(f"\n  {'a':>6}  {'c2':>13}  {'scatter':>9}  {'R^2':>10}  "
      f"{'mu2':>10}  {'beta':>10}  {'N used':>16}")
print("  " + "-" * 84)

results = {}
for a in (0.75, 0.72, 0.71, 0.70):
    cc, sd, rr, used = corrected(a, NS)
    if not np.isfinite(cc):
        print(f"  {a:6.2f}  {'Newton did not land at 3 or more resolutions':>13}"
              f"   used {used}")
        continue
    m = (cc - 1.0) / (a * cc)
    results[a] = (m + 1.0, sd, cc)
    print(f"  {a:6.2f}  {cc:13.8f}  {sd:9.1e}  {rr:10.7f}  {m:10.5f}  "
          f"{m + 1.0:10.5f}  {str(used):>16}")

print()
print("  Anchor: finding 12 gives beta = 4.2128337 at a = 0.75.")
if 0.75 in results:
    print(f"  This run gives {results[0.75][0]:.7f}, "
          f"differing by {results[0.75][0] - 4.2128337:+.2e}.")

print()
if 0.71 in results:
    b71 = results[0.71][0]
    print(f"  a = 0.71:  ours {b71:.5f}   theirs {P_B_LSS_071:.5f}   "
          f"difference {b71 - P_B_LSS_071:+.5f}  "
          f"({100.0 * (b71 - P_B_LSS_071) / P_B_LSS_071:+.2f} percent)")
else:
    print("  a = 0.71 did not converge, so no comparison is made. The frozen")
    print("  branch begins at their a_c = 0.68907 and the simulation seeded")
    print("  guess is weakest there; a continuation in a from 0.75 downward")
    print("  would be the way to reach it.")
print()
