"""
Is the linear growth an instability, or drift along the equilibrium manifold?

neutral.py found ||v|| growing linearly under v_t = M v, which with a purely
imaginary spectrum means a Jordan block at zero. There is an innocent
explanation. The equilibria form a two dimensional manifold, amplitude and
translation, and its tangent directions sin x and cos x are exactly the kernel
of M. A generic perturbation moves the state along that manifold at a constant
rate, so the kernel component accumulates linearly. That is drift, not
instability: the state stays on the set of steady states, just at a different
amplitude and phase.

The test is to project the kernel out at each time rather than only at the
start. If the remainder stays bounded while the kernel part grows linearly,
the picture is confirmed: neutral oscillation modulo the symmetries, with a
Jordan block generated by the symmetries themselves.

Either way the consequence for reduction is the same, and that is the point of
the exercise. No spectral gap means no fast modes to slave to slow ones, so
neither quasi steady elimination nor mode truncation is justified.

    python neutral2.py
"""

import numpy as np

import dg


def dR_apply(g, f, v, a):
    u_f, ux_f, fx_f = dg.fields(g, f)
    u_v, ux_v, vx = dg.fields(g, v)
    return g.bwd(g.fwd(v * ux_f + f * ux_v - a * (u_v * fx_f + u_f * vx)))


def rk4(g, f, v, dt, a):
    k1 = dR_apply(g, f, v, a)
    k2 = dR_apply(g, f, v + 0.5 * dt * k1, a)
    k3 = dR_apply(g, f, v + 0.5 * dt * k2, a)
    k4 = dR_apply(g, f, v + dt * k3, a)
    return v + (dt / 6.0) * (k1 + 2 * k2 + 2 * k3 + k4)


g = dg.Grid(512)
f = np.sin(g.x)
S, C = np.sin(g.x), np.cos(g.x)


def split(v):
    """Kernel part along sin x and cos x, and the remainder."""
    cs = (v @ S) / (S @ S)
    cc = (v @ C) / (C @ C)
    return cs, cc, v - cs * S - cc * C


rng = np.random.default_rng(3)
v = g.bwd(g.fwd(rng.normal(size=g.N)))
v -= v.mean()
_, _, v = split(v)
v /= np.abs(v).max()
r0 = float(np.linalg.norm(v))

print()
print(f"  {'t':>8}  {'along sin x':>13}  {'along cos x':>13}  "
      f"{'remainder':>12}  {'rem / t=0':>10}")
print("  " + "-" * 62)
cs, cc, rem = split(v)
print(f"  {0.0:8.1f}  {cs:13.5f}  {cc:13.5f}  "
      f"{np.linalg.norm(rem):12.5f}  {1.0:10.5f}")

dt, t = 1.0e-3, 0.0
for target in (10.0, 50.0, 100.0, 200.0, 400.0):
    while t < target - 1e-12:
        step = min(dt, target - t)
        v = rk4(g, f, v, step, 1.0)
        t += step
    cs, cc, rem = split(v)
    nr = float(np.linalg.norm(rem))
    print(f"  {t:8.1f}  {cs:13.5f}  {cc:13.5f}  {nr:12.5f}  {nr / r0:10.5f}")

print()
print("  Kernel components growing linearly while the remainder stays bounded")
print("  is drift along the manifold of equilibria, not instability. A")
print("  remainder growing too would mean a genuine secular instability.")
